name: Upload Prebuilt Zip (MoreCompany)

on:
  push:
    paths:
      - 'CHANGELOG.md'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  handleClient:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create CookiesMoreCompany Zip
        run: |
          sudo apt install zip
          zip -r CookiesMoreCompany.zip icon.png manifest.json README.md BepInEx CHANGELOG.md
      - id: pub
        uses: ./
        with:
          namespace: ChocolateCookies
          name: CookiesMoreCompany
          token: ${{ secrets.TS_KEY }}
          description: |
            🍪 [WORKS WITH v47 & v49] Full Support for More Company, includes all major add ons and patches, as well as many cosmetics for MoreCompany 🍪
          version: v1.${{ github.run_number }}.0
          community: lethal-company
          repo: thunderstore.io
          website: "https://creampies.wtf"
          categories: |
            cosmetics
            mods
            modpacks
          # Check the correct format for dependencies in Thunderstore
          deps: |
            ChocolateCookies-CookiesMoreCompany-1.${{ github.run_number }}.0
          file: ./CookiesMoreCompany.zip
      - run: echo ${{ steps.pub.outputs.url }}
